hyperparameters {
  fit_intercept: true
  intercept_scaling: 1.0
  multi_class: "auto"
  verbose: 0
  warm_start: false
  C: 1.0
  dual: false
  max_iter: 100
  penalty: "l2"
  solver: "lbfgs"
  tol: 0.0001
}
parameters {
  feature_names_in_: "age"
  feature_names_in_: "trtbps"
  feature_names_in_: "chol"
  feature_names_in_: "thalachh"
  feature_names_in_: "oldpeak"
  n_features_in_: 5
  classes_: 0
  classes_: 1
  n_iter_: 8
  coef_: "[[-0.13355927704885287, -0.10442842704594073, -0.033645072576336664, 0.6443604427769034, -0.9262713168889497]]"
  intercept_: 0.1661555
}
model_details {
  file_type: "Empty"
  Framework: "sklearn"
  Library: "sklearn.linear_model._logistic"
  Algorithm: "LogisticRegression"
}
