hyperparameters {
  fit_intercept: true
  intercept_scaling: 1.0
  multi_class: "auto"
  verbose: 0
  warm_start: false
  C: 1.0
  dual: false
  max_iter: 100
  penalty: "l2"
  solver: "lbfgs"
  tol: 0.0001
}
